packages:
  - packages/*

catalog:
  '@ckwalsh/typescript-dev-configs': ^1.0.2
  '@jest/globals': ^30.0.0
  '@tsconfig/node': npm:@tsconfig/node20@^20.1.6
  '@tsconfig/recommended': ^1.0.10
  '@types/node': ^20.19.1
  jest: ^30.0.0
  knip: ^5.61.2
  tsup: ^8.5.0
  ts-jest: ^29.4.0
  typescript: ^5.8.3

requiredScripts:
  - attw
  - build
  - build:watch
  - knip
  - lint
  - lint:fix
  - test
  - tsc
  - tsc:watch
