packages:
  - packages/*

catalog:
  '@ckwalsh/typescript-dev-configs': ^1.0.6
  '@jest/globals': ^30.2.0
  '@tsconfig/node': npm:@tsconfig/node20@^20.1.6
  '@tsconfig/recommended': ^1.0.13
  '@types/node': ^24.10.1
  jest: ^30.2.0
  knip: ^5.69.1
  tsup: ^8.5.1
  ts-jest: ^29.4.5
  typescript: ^5.9.3

requiredScripts:
  - attw
  - build
  - build:watch
  - clean
  - knip
  - lint
  - lint:fix
  - test
  - tsc
  - tsc:watch
