name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Build and Test

    permissions:
      contents: read

    runs-on: default

    timeout-minutes: 15

    env:
      HUSKY: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Use shared pnpm store
        run: |
          pnpm config set store-dir "$RUNNER_TOOL_CACHE/.pnpm-store"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Linter
        run: |
          pnpm run lint

      - name: Run knip
        run: |
          pnpm run knip

      - name: Build and Run attw
        run: |
          pnpm run attw

      - name: Run Tests
        run: |
          pnpm run test
