name: PR for main

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test (Node ${{ matrix.node-version }})

    permissions:
      contents: read

    runs-on: homelab

    strategy:
      fail-fast: false
      matrix:
        node-version: ['*', 'lts/*', 'lts/-1', 'lts/-2']

    env:
      HUSKY: 0
      CI: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dump environment variables
        run: env
        shell: bash

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Run Linter
        run: pnpm run lint
        shell: bash

      - name: Run Tests
        run: pnpm run test
        shell: bash

      - name: Run AreTheTypesWrong
        run: pnpm run attw
        shell: bash
