name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  github:
    runs-on: homelab
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          registry-url: 'https://npm.pkg.github.com'
      - uses: ./.github/actions/build.yml
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
