name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Build, Test, and Update Versions

    permissions:
      contents: read
      pull-requests: write

    runs-on: homelab
    environment: release

    timeout-minutes: 15

    env:
      HUSKY: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: |
          pnpm install
        shell: bash

      - name: Run Linter
        run: |
          pnpm run lint
        shell: bash

      - name: Run knip
        run: |
          pnpm run knip
        shell: bash

      - name: Build and Run attw
        run: |
          pnpm run attw
        shell: bash

      - name: Run Tests
        run: |
          pnpm run test
        shell: bash

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
